AllCops:
  RunRailsCops: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/test_helper.rb'
    - 'Guardfile'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
