MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
OveruseRouteCustomizationsCheck: { customize_count: 4 }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
RemoveUnusedMethodsInControllersCheck: { except_methods: [
  'RegistrationsController#account_update_params',
  'RegistrationsController#sign_up_params',
  'RegistrationsController#update_resource',
  'RegistrationsController#after_update_path_for',
  'ConfirmationsController#after_confirmation_path_for'
  ]
}
